#!/bin/bash
# Olist Database Deployment Guide

set -e

echo "🚀 Olist Database with PGVector - Deployment Guide"
echo "=================================================="

echo ""
echo "📋 Deployment Options:"
echo ""
echo "1️⃣  Quick Start with Docker Hub:"
echo "   docker pull cmcoutosilva/olist-db:latest"
echo "   curl -o docker-compose.yml https://raw.githubusercontent.com/cmcouto-silva/olist-db/main/docker-compose.yml"
echo "   docker compose up"
echo ""
echo "2️⃣  Local Development:"
echo "   git clone https://github.com/cmcouto-silva/olist-db.git"
echo "   cd olist-db && docker compose up"
echo ""
echo "3️⃣  Build Your Own Image:"
echo "   docker build -t your-username/olist-db ."
echo "   docker push your-username/olist-db"
echo ""
echo "4️⃣  EC2 Deployment (Secure):"
echo "   curl -o setup_db.sh https://raw.githubusercontent.com/cmcouto-silva/olist-db/main/scripts/setup_db.sh"
echo "   chmod +x setup_db.sh && ./setup_db.sh"
echo "   docker compose up -d"
echo ""
echo "🧪 Test PGVector:"
echo "   curl -o test_pgvector.sh https://raw.githubusercontent.com/cmcouto-silva/olist-db/main/scripts/test_pgvector.sh"
echo "   chmod +x test_pgvector.sh && ./test_pgvector.sh"
echo ""
echo "📚 Database Info:"
echo "   Host: localhost:5432"
echo "   Database: olist_ecommerce"
echo "   User: postgres"
echo "   Password: postgres (change in production!)"
echo ""
echo "🚀 Features:"
echo "   ✅ PostgreSQL 17 + PGVector extension"
echo "   ✅ 1.4M+ records with referential integrity"
echo "   ✅ Vector similarity search (<->, <#>, <=>)"
echo "   ✅ AI/ML ready for embeddings"
echo "   ✅ Complete schema documentation"
echo "   ✅ Automatic duplicate handling"
echo ""
echo "💡 Next Steps:"
echo "   • Connect with your favorite PostgreSQL client"
echo "   • Explore ecommerce and marketing schemas"
echo "   • Create vector embeddings for semantic search"
echo "   • Build recommendation systems with vector similarity" 
